exploradoresdemadrid/decide

Procfile
This file is needed to deploy the application to Heroku
=> Include Procfile

app/api_doc/v1/auth_doc.rb, app/controllers/api/v1/users/sessions_controller.rb, app/models/user.rb, db/migrate/20191217211836_add_auth_token_to_user.rb, db/schema.rb, public/open_api/swagger_doc.json, spec/factories/users_factory.rb, spec/models/user_spec.rb
We want to allow users to sign in using a plain 6-digit pin. This pin will expire 2 days after it was generated.
=> Implement pin-based authentication

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/main.scss, app/views/_navbar.html.erb, app/views/groups/index.html.erb, app/views/groups/show.html.erb, app/views/home/index.html.erb, app/views/layouts/application.html.erb, app/views/questions/_form.html.erb, app/views/questions/index.html.erb, app/views/questions/show.html.erb, app/views/votings/_form.html.erb, app/views/votings/index.html.erb, app/views/votings/show.html.erb
=> Generate basic tables and forms with Bootstrap

app/controllers/groups_controller.rb, app/views/_navbar.html.erb, app/views/groups/_form.html.erb, app/views/groups/index.html.erb
- Groups table has been enhanced using Bootstrap tables
- Groups form has been enhanced using Bootstrap forms
- A link to Groups list has been included in the navbar
=> Enhance groups UI

app/models/group.rb, app/models/user.rb, app/views/groups/index.html.erb, db/migrate/20191225232950_add_user_to_group.rb, db/migrate/20191225234818_add_trackable_to_devise.rb, db/schema.rb, spec/models/group_spec.rb
We need to authenticate the users that represent each of the groups. For that reason, a user will be automatically created associated to the group
=> Group Users

app/api_doc/v1/groups_doc.rb, app/controllers/groups_controller.rb, app/serializers/group_serializer.rb, config/routes.rb, public/open_api/swagger_doc.json
We need to expose information about the group of the user who is logged in so that we can display the right amount of available votes.
=> Expose information about the current logged-in group via API

app/controllers/questions_controller.rb
We were displaying all the questions in the questions list, no matter the voting that was being visited.
Scoping the questions by voting.
=> Scope the questions displayed to the current voting

app/controllers/application_controller.rb, config/initializers/devise.rb
There was an issue with the login / logout redirections. New behavior is:
- The user is redirected to the votings list after a successful login.
- The user is redirected to the root path (the documentation page) after a successful logout.
=> Fix redirection issues

app/models/user.rb
We need to disable user registration since all users have admin access by default.
Removing that option from the model using devise, as stated in [this response](https://stackoverflow.com/a/44489551/3607039) in SO
=> Disable user registration

app/api_doc/v1/votings_doc.rb, app/controllers/application_controller.rb, app/models/group.rb, app/serializers/voting_serializer.rb, public/open_api/swagger_doc.json
We need to provide information about whether the current group has already voted or not.
=> Include information in the voting API

app/controllers/api/v1/users/sessions_controller.rb, app/controllers/sessions_controller.rb, app/views/sessions/new.html.erb, config/routes.rb
Groups need to be able to sign in using a token instead of regular email / password
=> Implement token login

app/assets/stylesheets/options.scss, app/views/questions/_form.html.erb, app/views/questions/_option_fields.erb, db/seeds.rb, docker-compose.yml
Several fixes are included in this PR:
- Hot reloading while developing with docker-compose
- Weird behavior adding options to a question (cocoon gem usage)
- Fixes in seeds file
=> Fix issues related with adding options to a question

.circleci/config.yml, Dockerfile-prod, config/database.yml
Prepare a Dockerfile to generate images that would be used in production environment
=> Configure dockerfile for production

config/database.yml
Allow specifying database username with environment variables
=> Allow specifying database username with environment variables

README.md
Remove default README and include CirlceCI status badge
=> Remove default README and include CirlceCI status badge

app/controllers/votings_controller.rb, app/helpers/votings_helper.rb, app/models/multiselect_voting.rb, app/models/option.rb, app/models/question.rb, app/models/simple_voting.rb, app/models/voting.rb, app/services/vote_submission_service.rb, app/views/votings/_form.html.erb, app/views/votings/_vote_submission_form.html.erb, app/views/votings/index.html.erb, db/migrate/20200505184003_add_sti_to_votings.rb, db/migrate/20200505185343_add_fields_to_multiselect_voting.rb, db/schema.rb, spec/factories/votings_factory.rb, spec/models/multiselect_voting_spec.rb
There are some votings where instead of answering yes/no to each of the options, the users may choose to support certain initiatives and not support some others. We need to modify the application to support this kind of votings.
=> Multiselect voting

app/views/votings/index.html.erb
Voting type should only be displayed to admins
=> Display voting type only to admins

app/helpers/votings_helper.rb, app/views/votings/show.html.erb
We need to use a different display for multiselect votings that reflect how many votes each of the options received.
=> Use a different display for multiselect votings

Gemfile, Gemfile.lock, app/models/jwt_blacklist.rb, app/models/user.rb, config/initializers/devise.rb, db/migrate/20200613112150_remove_devise_jwt.rb, db/schema.rb
We are no longer using devise JWT gem
=> Remove devise-jwt gem

app/views/layouts/application.html.erb, app/views/layouts/mailer.html.erb, public/404.html, public/422.html, public/500.html
From SonarCloud, 
> It enables assistive technologies, such as screen readers, to provide a comfortable reading experience by adapting the pronunciation and accent to the language. It also helps braille translation software, telling it to switch the control codes for accented characters for instance.
=> Add lang HTML headers

.circleci/config.yml
Deploy decide master branch to production environment
=> Configure project to deploy master branch

app/models/voting.rb, app/views/votings/_vote_submission_form.html.erb, app/views/votings/show.html.erb, config/locales/en.yml, config/locales/es.yml, cypress/integration/votings/vote.spec.js, package.json, spec/models/voting_spec.rb, spec/services/vote_submission_service_spec.rb
Visual part implemented. New state "ready".
Fixes  #255.
=> Fixed: #255 "Ready" status for votings

app/controllers/groups_controller.rb, app/services/csv_group_importer.rb, app/views/groups/bulk_upload_show.erb, app/views/groups/index.html.erb, config/locales/en.yml, config/locales/es.yml, config/routes.rb, cypress/integration/groups/group_import_csv.js, spec/fixtures/groups/.~lock.valid_import.csv#, spec/fixtures/groups/invalid_empty_line.csv, spec/fixtures/groups/invalid_extra_columns.csv, spec/fixtures/groups/invalid_no_header.csv, spec/fixtures/groups/invalid_wrong_information.csv, spec/fixtures/groups/valid_import.csv, spec/services/csv_group_importer_spec.rb
Implement a process to import groups from a CSV file.
Fixes #281
=> Basic implementation of bulk group creation

app/controllers/votings_controller.rb, app/helpers/votings_helper.rb, app/models/voting.rb, app/views/votings/index.html.erb, app/views/votings/show.html.erb, cypress/integration/votings/vote.spec.js, cypress/support/commands.js, spec/models/voting_spec.rb
Move archived votings to a different view
Fixes #256
=> Include archived status

app/controllers/application_controller.rb, app/controllers/groups_controller.rb, app/controllers/organizations_controller.rb, app/controllers/questions_controller.rb, app/controllers/sessions_controller.rb, app/controllers/votings_controller.rb, app/helpers/votings_helper.rb, app/models/ability.rb, app/views/_navbar.html.erb, app/views/groups/_form.html.erb, app/views/groups/edit.html.erb, app/views/groups/index.html.erb, app/views/groups/new.html.erb, app/views/layouts/application.html.erb, app/views/questions/_form.html.erb, app/views/questions/edit.html.erb, app/views/questions/index.html.erb, app/views/questions/new.html.erb, app/views/votings/_form.html.erb, app/views/votings/_vote_submission_form.html.erb, app/views/votings/edit.html.erb, app/views/votings/index.html.erb, app/views/votings/new.html.erb, app/views/votings/show.html.erb, config/routes.rb, cypress/integration/groups/reset_token_spec.js, cypress/integration/organizations/organization_visibility_spec.js, cypress/integration/questions/create_questions.spec.js, cypress/integration/votings/create_voting.spec.js, cypress/support/commands.js
Even though groups and votings are conceptually nested models of an organization, the routes do not reflect it. We need to update the way that route structure.
=> Modify route structure to match nested resources

cypress/support/commands.js
There is a test case that fails frequently as a consequence of some changes in the translations
=> Increase stability of cypress specs

config/environments/production.rb
We want to enable the security features like HSTS and secure cookies in production environment
=> Enable secure features

config/environments/production.rb
Reverts exploradoresdemadrid/decide#314
=> Revert "Enable secure features"

app/models/group.rb, app/views/groups/index.html.erb, cypress/integration/groups/create_group_spec.js
=> Fix group deletion

app/controllers/organizations_controller.rb, app/models/ability.rb, app/models/organization.rb, app/views/organizations/_form.html.erb, app/views/organizations/index.html.erb, config/locales/activerecord.en.yml, config/locales/activerecord.es.yml, cypress/integration/organizations/create_organization_spec.js, cypress/support/commands.js, spec/factories/organizations_factory.rb
=> Display list of admins for each organization

app/assets/javascripts/voting.js, cypress/integration/groups/create_group_spec.js
Change var declarations to let.
=> Fix var declaration to let

app/controllers/groups_controller.rb, app/models/organization.rb, app/services/csv_group_exporter.rb, app/views/groups/bulk_upload_show.erb, config/locales/en.yml, config/locales/es.yml, config/routes.rb, spec/services/csv_group_exporter_spec.rb
We want to provide a CSV template export so that organizations can download, fill and upload it to create their groups
=> CSV data export for groups

app/models/bodies_group.rb, app/models/group.rb, app/services/csv_group_exporter.rb, app/services/csv_group_importer.rb, app/views/groups/bulk_upload_show.erb, app/views/groups/index.html.erb, config/locales/en.yml, config/locales/es.yml, cypress/integration/groups/group_import_csv.js, cypress/integration/groups/reset_token_spec.js, spec/fixtures/groups/invalid_empty_line.csv, spec/fixtures/groups/invalid_extra_columns.csv, spec/fixtures/groups/invalid_no_header.csv, spec/fixtures/groups/invalid_wrong_information.csv, spec/fixtures/groups/valid_import.csv, spec/fixtures/groups/valid_import_create.csv, spec/services/csv_group_importer_spec.rb
We need to update the CSV import process to match the format of the new export.
=> Adapt import process to the new file structure

app/assets/javascripts/voting.js, app/assets/stylesheets/main.scss, app/helpers/application_helper.rb, app/views/groups/index.html.erb, app/views/layouts/application.html.erb, config/locales/activerecord.en.yml, config/locales/activerecord.es.yml
We want to be able to identify groups that do not have an email configured, since they will not be able to get the access code via email.
=> Display a warning when a group is missing email

cypress.json
We want to enable test retries to be able to detect the flaky tests while reducing manual retry launches.
Docs: https://docs.cypress.io/guides/guides/test-retries.html#Global-Configuration
=> Enable cypress retries to detect flaky tests

app/controllers/api/v1/application_controller.rb, app/controllers/api/v1/organizations_controller.rb, app/controllers/groups_controller.rb, app/models/organization.rb, config/locales/en/en.yml, config/locales/es/es.yml, config/routes.rb
We want to be able to create test organizations via API so that we can run automated security tests on them.
=> Test account in production

Gemfile, Gemfile.lock
We want to use the bullet gem in the development environment to easily detect N+1 queries.
=> Add bullet gem

app/models/group.rb, spec/models/group_spec.rb
We want to remove the constraint that prevents two groups from having the same name or email.
=> Allow groups with same name and email

app/views/votings/_vote_submission_form.html.erb, config/locales/en/en.yml, config/locales/es/es.yml
Display a message indicating that observer accounts cannot vote.
Fixes #299
=> Display a special message for observer accounts

app/models/question.rb
We need to be able to order questions within a voting. We are adding a default scope to order by title.
=> Order questions by title by default

Gemfile.lock
Reverts exploradoresdemadrid/decide#454
=> Revert "build(deps-dev): bump simplecov from 0.21.1 to 0.21.2"

cypress/integration/groups/create_group_spec.js, cypress/integration/groups/group_import_csv.js, cypress/integration/login/admin_login.spec.js, cypress/integration/login/group_login.spec.js, cypress/integration/organizations/create_organization_spec.js, cypress/integration/questions/create_questions.spec.js, cypress/integration/votings/vote.spec.js
We will run out of quota sooner than expected.
=> Reduce number of percy screenshots

.circleci/config.yml
We need to fix an issue installing Postgres' local libraries
=> Fix issue installing local dependencies in CircleCI

app/helpers/votings_helper.rb, config/locales/en/en.yml, config/locales/es/es.yml
There is a bug in the current display:
=> Fix display of multiselect options
