app/models/option.rb, app/models/question.rb, app/models/voting.rb
We need to destroy all models associated with a voting object when it is destroyed.
=> Configure cascade deletion on models associated to votings

app/controllers/api/v1/users/sessions_controller.rb, app/views/groups/index.html.erb
Last login tracking was not working properly for API login
- Manually trigger the tracking of user data after API sign in
- Modify the groups list page to display the last sign in datetime in relative terms.
=> Fix last login tracking using API

docker-compose.yml
docker-compose could not run the migrations because there was an error creating the database
=> Skip db creation step from docker-compose file

app/models/user.rb, spec/models/user_spec.rb
Normally we need to configure the authentication tokens during the week before the votings actually happen. Two days are not time enough to configure the tokens during working hours if the voting takes place on Sundays.
=> Increase token duration to one week

app/models/group.rb, db/migrate/20200506221148_make_group_number_optional.rb, db/schema.rb, spec/models/group_spec.rb
_Decide_ is going to be use by organizations where groups do not have an associated number. For this reason, this field should be made optional.
=> Make group number optional

app/models/multiselect_voting.rb, spec/models/multiselect_voting_spec.rb
An error occurs while creating multiselect votings without providing any option:
```
2020-05-06T22:48:15.519802+00:00 app[web.1]: [7e584834-5694-4dfd-b9b1-8d248a426612] NoMethodError (undefined method `split' for nil:NilClass):
2020-05-06T22:48:15.519803+00:00 app[web.1]: [7e584834-5694-4dfd-b9b1-8d248a426612]
2020-05-06T22:48:15.519804+00:00 app[web.1]: [7e584834-5694-4dfd-b9b1-8d248a426612] app/models/multiselect_voting.rb:36:in `handle_options'
2020-05-06T22:48:15.519804+00:00 app[web.1]: [7e584834-5694-4dfd-b9b1-8d248a426612] app/controllers/votings_controller.rb:36:in `create'
```
=> Fix error creating multiselect votings without options

app/models/multiselect_voting.rb, spec/models/multiselect_voting_spec.rb
Multiselect votings are incorrectly separating options by words in addition to by lines
=> Fix incorrect split of options by space

app/views/votings/_question_results.html.erb
Information about the vote emitted is redundant in non-secret votings, and misleading in secret ones.
=> Stop displaying info about the sense of the votes emitted

app/helpers/application_helper.rb
The voting results page contains a list of the groups that have already voted and those that have not voted yet. However, when the list os long it is hard to know how many groups are pending to vote.
=> Use ordered lists in the voting resusts page

app/models/voting.rb
The normal workflow of votings is: 
1. Draft
1. Ready
1. Open
1. Finished
1. Archived
However, the status dropdown in the voting form was displaying _open_ before _ready_, which is a bit confusing. This PR swaps those elements in the `enum` definition, which affects the way the dropdown is generated.
=> Reorder voting dropdown to match the chronological order

app/views/votings/show.html.erb, cypress/integration/votings/vote.spec.js
The message that indicates that a user has already voted was red, which should be reserved for errors or dangerous operations. The style has now changed to the green "success" one.
=> Indicate that the user has already voted with a green friendly message

config/initializers/devise.rb
We want to configure the _secure_ flag to session cookies to make sure they only travel through HTTPS connections.
=> Configure segure flag for devise session

config/application.rb
Remove runtime middleware to avoid timing attacks using the `x-runtime` header. Reference: https://www.virtuesecurity.com/kb/x-runtime-header-timing-attacks/
=> Remove runtime middleware to avoid timing attacks

config/initializers/devise.rb
Reverts exploradoresdemadrid/decide#316. The configuration is not working as expected.
=> Revert "Configure segure flag for devise session"

spec/models/user_spec.rb
There is one test that is failing locally because it is using the host's timezone
```
Failures:
1) User auth_token expires after 7 days
Failure/Error:
expect(user.auth_token_expires_at).to be_between(
(Time.now + 7.days - 1.second),
(Time.now + 7.days + 1.second)
)
expected 2020-10-30 15:53:51.450677061 +0000 to be between 2020-10-30 17:53:50.452744391 +0100 and 2020-10-30 17:53:52.452860699 +0100 (inclusive)
```
=> Fix error running spec in a different timezone

config/environments/production.rb
We need to configure a default host for email delivery:
```
ActionView::Template::Error: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
```
=> Configure default host

app/helpers/mail_helper.rb
Fix an error generating the email for groups:
```
2020-10-29T23:33:39.607Z pid=1 tid=pf1 WARN: /app/app/helpers/mail_helper.rb:13:in `each'
/app/app/helpers/mail_helper.rb:13:in `inject'
/app/app/helpers/mail_helper.rb:13:in `plain_mail_vote_distribution'
/app/app/views/group_mailer/code_submission.es.text.erb:7:in `_app_views_group_mailer_code_submission_es_text_erb___1562117738975366436_33500'
/usr/local/bundle/gems/actionview-6.0.3.4/lib/action_view/base.rb:274:in `_run'
/usr/local/bundle/gems/actionview-6.0.3.4/lib/action_view/template.rb:185:in `block in render'
/usr/local/bundle/gems/activesupport-6.0.3.4/lib/active_support/notifications.rb:182:in `instrument'
/usr/local/bundle/gems/actionview-6.0.3.4/lib/action_view/template.rb:385:in `instrument_render_template' …
```
=> Fix error joining available votes in email

app/mailers/group_mailer.rb, app/views/layouts/mailer.html.erb, app/views/layouts/mailer.text.erb
We want to change the email signature using the organization name instead of a fixed "Exploradores de Madrid".
=> Use organization name in emails signature

app/helpers/options_helper.rb, app/helpers/questions_helper.rb, app/models/organization.rb, app/models/question.rb, app/services/vote_submission_service.rb, app/views/votings/_vote_submission_form.html.erb, db/seeds.rb, package.json, spec/services/vote_submission_service_spec.rb
Organizations now support multiple decision-making bodies, each of them with a different number of votes available per group. We should no longer use the available votes configured at the group level.
=> Use number of votes in the specific body

app/controllers/groups_controller.rb, app/helpers/votings_helper.rb, app/models/group.rb, app/services/csv_group_importer.rb, app/views/groups/_form.html.erb, config/locales/en/activerecord.en.yml, cypress/integration/groups/create_group_spec.js, cypress/support/commands.js, db/migrate/20201113172351_remove_votes_column.rb, db/schema.rb, db/seeds.rb, spec/factories/groups_factory.rb, spec/models/group_spec.rb, spec/services/vote_submission_service_spec.rb
Now that the application supports multiple decision-making bodies, it no longer makes sense to use the `available_votes` column in the Group model. It can be destroyed along with all usages.
=> Remove votes column

db/migrate/20201113182415_remove_database_uniqueness_constraints.rb, db/schema.rb
When the constraint to allow multiple groups with the same name was removed, we forgot to remove the BD constraint
```
ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_groups_on_name"
```
=> Add a migration to remove the uniqueness db constraint on group name

app/assets/stylesheets/main.scss, app/helpers/votings_helper.rb, app/models/question.rb, app/models/voting.rb, config/locales/en/activerecord.en.yml, config/locales/es/activerecord.es.yml, spec/models/question_spec.rb, spec/models/voting_spec.rb
We need to make admins aware when a voting is misconfigured so that they fix it before opening it. A voting is considered to be misconfigured when any of the following conditions are met:
1. The voting has no questions.
1. Any of the questions has less than two options to choose from.
=> Warn about misconfigured votings

app/models/voting.rb, app/views/votings/_countdown_component.html.erb, app/views/votings/_vote_submission_form.html.erb, config/routes.rb, spec/models/voting_spec.rb
There are some issues related to the countdown component. Specifically, this PR fixes:
* Display the countdown component only in those votings that have a timeout configured.
* Re-enable the countdown timer when there is a voting transition from finished to open.
* Enable Sidekiq view in the development environment.
* Remove misleading timeout information when the component is first loaded.
=> Fix countdown issues

app/helpers/votings_helper.rb, config/locales/en/activerecord.en.yml, config/locales/es/activerecord.es.yml
There was a big gap between 1 minute and 5 minutes in the dropdown list for the countdown. This PR adds the 2-minute and 3-minute options
=> Add more options in the timeout dropdown

app/controllers/votings_controller.rb
The votings in the votings index did not have a specific order, so it was difficult to make them show up in the same order they are going to be opened.
We decided to order by name so that we can prepend the desired order to the title of the voting. In future developments, a date field may be added, which will take precedence over the title.
=> Order votings by name
